name: Обновление файла http_proxy

on:
  push:
    branches:
      - main

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Установка зависимостей
        run: pip install requests

      - name: Запуск Python скрипта
        run: python path/to/your/script.py

      - name: Обновление файла http_proxy.txt
        run: |
          echo ${{ steps.script.outputs.data }} > http_proxy.txt
